package com.kolloseum.fourpillars.application.service.impl;

import com.kolloseum.fourpillars.application.service.AdminTermsService;
import com.kolloseum.fourpillars.common.utils.HtmlSanitizer;
import com.kolloseum.fourpillars.domain.model.entity.Terms;
import com.kolloseum.fourpillars.domain.model.enums.TermsType;
import com.kolloseum.fourpillars.infrastructure.persistence.entity.TermsEntity;
import com.kolloseum.fourpillars.infrastructure.persistence.mapper.TermsMapper;
import com.kolloseum.fourpillars.infrastructure.persistence.repository.TermsJpaRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

@Slf4j
@Service
@RequiredArgsConstructor
public class AdminTermsServiceImpl implements AdminTermsService {

    private final TermsJpaRepository termsJpaRepository;
    private final HtmlSanitizer htmlSanitizer;

    @Override
    @Transactional
    public void createTerms(TermsType type, String version, String content) {
        String sanitizedContent = htmlSanitizer.sanitize(content);
        String fileHash = calculateSha256(sanitizedContent);

        Terms terms = Terms.restore(
                null, // ID is generated by DB
                type,
                version,
                sanitizedContent,
                fileHash,
                LocalDateTime.now());

        TermsEntity entity = TermsMapper.toEntity(terms);
        termsJpaRepository.save(entity);

        log.info("Admin created new terms: type={}, version={}, hash={}", type, version, fileHash);
    }

    private String calculateSha256(String content) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] encodedhash = digest.digest(content.getBytes(StandardCharsets.UTF_8));
            return bytesToHex(encodedhash);
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("SHA-256 algorithm not found", e);
        }
    }

    private String bytesToHex(byte[] hash) {
        StringBuilder hexString = new StringBuilder(2 * hash.length);
        for (byte b : hash) {
            String hex = Integer.toHexString(0xff & b);
            if (hex.length() == 1) {
                hexString.append('0');
            }
            hexString.append(hex);
        }
        return hexString.toString();
    }

    @Override
    @Transactional(readOnly = true)
    public List<Terms> getAllTerms() {
        return termsJpaRepository.findAllByOrderByCreatedAtDesc().stream()
                .map(TermsMapper::toDomain)
                .collect(Collectors.toList());
    }
}
